version: '3.1'

services:
  db:
    image: mariadb:11.4
    # container_name: db
    restart: always
    volumes:
      - "./mariadb:/var/lib/mysql"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=user
      - MARIADB_PASSWORD=user
    networks:
      - pman

  phpmyadmin:
    image: phpmyadmin:5.1.3
    restart: always
    ports:
      - 8080:80
    links:
      - db:db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    networks:
      - pman
networks:
  pman: {}


#  docker inspect -f '{{.Name}} - {{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(docker ps -aq)